### ISSUE TITLE
assertion failed

### ISSUE THREAD

**Issue by XinaTheThird** [SutandoTsukai181/YakuzaParless#8]
whenever i try to launch yk2 with mods it always gives me this 
![unknown-5](https://user-images.githubusercontent.com/102587311/164225789-055c5f0c-80c2-4beb-8f46-a99118d17dda.png)
im on the windows 10 version (dumped)

**Comment by mosamadeeb** [comment]
Windows 10 (UWP) versions of games are not exactly supported for now. Use the Steam versions instead.
